name: Daily AI News to Slack

on:
  schedule:
    - cron: '0 22 * * *'  # 日本時間7:00（UTC+9 → UTC=22:00）
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requests
        run: pip install requests

      - name: Run the news script
        run: python script.py
        env:
          GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
